// class Autogenerated {
//   int? status;
//   Null? error;
//   Data? data;

//   Autogenerated({this.status, this.error, this.data});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     error = json['error'];
//     data = json['data'] != null ? new Data.fromJson(json['data']) : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['status'] = this.status;
//     data['error'] = this.error;
//     if (this.data != null) {
//       data['data'] = this.data!.toJson();
//     }
//     return data;
//   }
// }

// class Data {
//   Audience? audience;

//   Data({this.audience});

//   Data.fromJson(Map<String, dynamic> json) {
//     audience = json['audience'] != null
//         ? new Audience.fromJson(json['audience'])
//         : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.audience != null) {
//       data['audience'] = this.audience!.toJson();
//     }
//     return data;
//   }
// }

// class Audience {
//   int? id;
//   String? name;
//   List<Contacts>? contacts;
//   String? createdAt;
//   Null? deletedAt;
//   int? userId;

//   Audience(
//       {this.id,
//       this.name,
//       this.contacts,
//       this.createdAt,
//       this.deletedAt,
//       this.userId});

//   Audience.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     if (json['contacts'] != null) {
//       contacts = <Contacts>[];
//       json['contacts'].forEach((v) {
//         contacts!.add(new Contacts.fromJson(v));
//       });
//     }
//     createdAt = json['created_at'];
//     deletedAt = json['deleted_at'];
//     userId = json['user_id'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     if (this.contacts != null) {
//       data['contacts'] = this.contacts!.map((v) => v.toJson()).toList();
//     }
//     data['created_at'] = this.createdAt;
//     data['deleted_at'] = this.deletedAt;
//     data['user_id'] = this.userId;
//     return data;
//   }
// }

// class Contacts {
//   String? name;
//   String? phone;

//   Contacts({this.name, this.phone});

//   Contacts.fromJson(Map<String, dynamic> json) {
//     name = json['name'];
//     phone = json['phone'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['name'] = this.name;
//     data['phone'] = this.phone;
//     return data;
//   }
// }