
# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end


default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:910308137326:android:ed2797d355220ab486097f",
       firebase_cli_token: "1//03ZNaF5bILPuMCgYIARAAGAMSNwF-L9IrzrQSSqIOBKIu1xt7ckoftvTFbu8_MSHlPcRPGuREc8uWPY6cUsb7Te7z9Qd04CVBqE0",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       testers: "samy.elmenshawy96@gmail.com",
       release_notes: "YOUR_RELEASE_NOTES_HERE"
     )
   end
 end